server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nagi1867/config-server
          #username: xxx
          #password: xxx
          default-label: main
          search-paths:
            - 'greeting-service*'